import fs from "node:fs";
import path from "node:path";

export interface NoteMeta {
  slug: string;
  title: string;
  summary: string;
  group: string;
  tags: string[];
  links: string[];
  backlinks: string[];
}

const dir = path.join(process.cwd(), "content", "notes");
const indexPath = path.join(dir, "_index.json");

// Generated by scripts/sync-notes.mjs and committed. Read at build time.
export function getNotes(): NoteMeta[] {
  if (!fs.existsSync(indexPath)) return [];
  return JSON.parse(fs.readFileSync(indexPath, "utf8")) as NoteMeta[];
}

export function getNote(
  slug: string,
): { meta: NoteMeta; content: string } | null {
  const meta = getNotes().find((n) => n.slug === slug);
  if (!meta) return null;
  const file = path.join(dir, `${slug}.md`);
  if (!fs.existsSync(file)) return null;
  return { meta, content: fs.readFileSync(file, "utf8") };
}

export function noteTitle(slug: string): string {
  return getNotes().find((n) => n.slug === slug)?.title ?? slug;
}
